Backend/loans/urls.py
from django.urls import path
from . import views
urlpatterns = [
path('', views.loan_home_view,name='loans-home'),
path('crear/', views.loan_create_view,name='loans-crear'),
path('buscar/', views.loan_search_view,name='loans-buscar'),
path('get/ajax/validate/tabla', views.tabla_prestamo, name = "tabla_prestamo")
]

Backend/pawnshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('loans/', include('loans.urls')),
    path('clients/', include('clients.urls')),
    path('abonos/', include('abonos.urls')),
    path('adicionales/', include('adicionales.urls')),
]

Backend/loans/models.py
from django.db import models
import datetime
from datetime import timedelta
# from django.core.validators import RegexValidator
from django.core.validators import MinValueValidator,MaxValueValidator
from clients.models import Client
from django.conf import settings

User = settings.AUTH_USER_MODEL

def get_deadline(date_created:int,num_meses:int):
    return timedelta(date_created) + timedelta(30*int(num_meses))

# Create your models here.
class TipoPago(models.Model):
    tipo = models.CharField(max_length=200)

    def __str__(self):
        return self.tipo

class Loan(models.Model):
    cliente         = models.ForeignKey(Client, on_delete=models.CASCADE)
    monto_prestado  =  models.PositiveIntegerField(validators=[MaxValueValidator(1000000000)],default=0)
    interes         = models.FloatField(
                        validators=[MinValueValidator(0.0), MaxValueValidator(10.0)],default=0
                    )
    num_meses       = models.PositiveIntegerField(validators=[MaxValueValidator(12)],default=1)
    tipo_pago       = models.ForeignKey(TipoPago, on_delete=models.CASCADE)

    date_created    = models.DateField()      

    num_cuotas      = models.PositiveIntegerField(validators=[MaxValueValidator(1000)],default=1)

    deadline = models.DateField()
    status = models.BooleanField(default=1) #NOTE: Estado del Prestamo 1 = activo, 2 = Inactivo
    last_modification = models.DateField(default=datetime.date.today)
    creador = models.ForeignKey(User,
                        null = True, 
                        on_delete = models.SET_NULL
                        )
    monto_adeudado   = models.PositiveIntegerField(default=0)
    
        
    def __str__(self):
        return f"{self.cliente}: {self.monto_prestado} - {self.date_created}"
    
    class Meta:
        ordering = ('pk',)

Backend/loans/views.py
from django.shortcuts import render, redirect
from .form import LoanForm
from .models import TipoPago
from clients.models import Client
from .models import Loan
from django.http import JsonResponse

def loan_create_view(request):
    form = LoanForm()

    if request.method == 'POST':
        print(request.POST)
        form = LoanForm(request.POST)
        if form.is_valid():
            print('Is valid')
            form.save()
            return redirect('/loans/')  # 4
        else:  # 5
            # Create an empty form instance
            form = LoanForm()
    tipo_pagos = TipoPago.objects.all().order_by('pk')
    clientes = Client.objects.all().order_by('nombre')

    context = {
        'form': form,
        'tipo_pagos': tipo_pagos,
        'clientes': clientes,
        }
    return render(request, 'loans/prestamos_crear.html', context)


def loan_home_view(request):
    clientes = Client.objects.all().order_by('pk')
    prestamos = Loan.objects.all().order_by('pk')

    context = {
        'clientes': clientes,
        'prestamos': prestamos,

         }
    return render(request, 'loans/prestamos_home.html', context)

def loan_search_view(request):
    return render(request, 'loans/prestamos_buscar.html', {})


def tabla_prestamo(request):
    if request.is_ajax and request.method == "GET":
        tables = []
        loans_table = Loan.objects.values()
        for prestamo in loans_table:
            # cliente = list(Client.objects.filter(pk=prestamo.cliente))
            cliente_nombre = list(Client.objects.filter(pk=prestamo["cliente_id"]).values())[0]["nombre"]
            cliente_apellido = list(Client.objects.filter(pk=prestamo["cliente_id"]).values())[0]["apellido"]
            tables.append(
                f'<tr><th scope="row">{prestamo["id"]}</th><td>{prestamo["monto_prestado"]}</td><td>{prestamo["monto_adeudado"]}</td><td>{prestamo["num_meses"]}</td><td>{prestamo["cliente_id"]}</td><td>{cliente_nombre} {cliente_apellido}</td></tr>'
            )
        
        return JsonResponse({"_prestamo_imformacion":tables}, status = 200)

        
    return JsonResponse({}, status = 400)

Backend/templates/loans/prestamos_buscar.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}
<title>Add loan | Django site admin</title>
{% endblock title %}

{% block css %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/loan/base.css' %}"
/>

<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/loan/forms.css' %}"
/>

<meta
  name="viewport"
  content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0"
/>

<meta name="robots" content="NONE,NOARCHIVE" />

{% endblock css %} 

{% block javascript %}
{% endblock javascript %}



{% block content %} 
<h1>Este es la busqueda de prestamos</h1>
{% endblock content %}

Backend/templates/loans/prestamos_crear copy.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}
<title>Add loan</title>

<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>

<link href= "{% static 'css/autocomplete/jquery-ui.css' %}"
    rel="stylesheet" type="text/css" />  
{% endblock title %}

{% block css %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/loan/base.css' %}"
/>

<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/loan/forms.css' %}"
/>

<meta
  name="viewport"
  content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0"
/>

<meta name="robots" content="NONE,NOARCHIVE" />

{% endblock css %} 

{% block javascript %}
{% endblock javascript %}


{% block content %} 
  <!-- Content -->
  <div id="content" class="colM">
    <h1>Agregar préstamo</h1>

    <div id="content-main">
      <form method="post" id="loan_form" novalidate="">
        {% csrf_token %}
        <div>
          <fieldset class="module aligned">
            <div class="form-row field-id">
              <div>

                <label class="required" for="id_pk"
                  >ID:</label
                >

                <div class="related-widget-wrapper">
                  <input type="text" id="client-id" name="cliente" >
                    <script>
                      $(function () {
                        var availableTags = [
                          {% for cliente in clientes %}
                          {
                            nombre: "{{cliente.nombre}}",
                            label: "{{cliente.pk}}",
                            last_name: "{{cliente.apellido}}",
                          },
                          {% endfor %}
                          // "{{cliente.pk}} {{cliente.nombre}} {{cliente.apellido}}",
                          // "{{cliente.nombre}}",
                        ];
                        $("#client-id")
                          .autocomplete({
                            minLength: 0,
                            source: availableTags,
                            focus: function (event, ui) {
                              $("#client-id").val(ui.item.label);
                              return false;
                            },
                            select: function (event, ui) {
                              $("#cliente-name").val(ui.item.nombre + " " + ui.item.last_name);
                              $("#client-id").val(ui.item.label);
                              return false;
                            },
                          })
                          .autocomplete("instance")._renderItem = function (ul, item) {
                          return $("<li>")
                            .append(
                              "<div>" +
                                item.label +
                                " " +
                                item.nombre +
                                " " +
                                item.last_name +
                                "</div>"
                            )
                            .appendTo(ul);
                        };
                      });
                    </script>
                </div>
              </div>
            </div>
            
            <div class="form-row field-cliente">
              <div>
                
                <label class="required" for="id_cliente"
                  >Cliente:</label
                >

                <div class="related-widget-wrapper">
                  <input type="text" id="cliente-name" >
                  <!-- <input type="hidden" id="client-id" name="cliente"> -->
                    <script>
                      $( function() {
                            var availableTags = [
                            {% for cliente in clientes %}
                            {
                              value: "{{cliente.pk}}",
                              label: "{{cliente.nombre}}",
                              last_name: "{{cliente.apellido}}",
                            },
                            {% endfor %}
                            // "{{cliente.pk}} {{cliente.nombre}} {{cliente.apellido}}",
                            // "{{cliente.nombre}}",
                            ];
                            $( "#cliente-name" ).autocomplete({
                                                            minLength: 1,
                                                            source: availableTags,
                                                            focus: function( event, ui ) {
                                                              $( "#cliente-name" ).val( ui.item.value + ' ' + ui.item.label + ' ' + ui.item.last_name );
                                                              return false;
                                                            },
                                                            select: function( event, ui ) {
                                                                                            $( "#cliente-name" ).val( ui.item.label + ' ' + ui.item.last_name );
                                                                                            $( "#client-id" ).val( ui.item.value );                  
                                                                                            return false;
                                                                                          }
                                                          })
                            .autocomplete( "instance" )._renderItem = function( ul, item ) {
                            return $( "<li>" )
                              .append( "<div>" + item.value + " " + item.label + " " + item.last_name + "</div>" )
                              .appendTo( ul );
                              };
                        } );
                      </script>


                  
                </div>
              </div>
            </div>

            <div class="form-row field-monto_prestado">
              <div>
                <label class="required" for="id_monto_prestado"
                  >Monto prestado:</label
                >

                <input
                  type="date"
                  name="date_created"
                  value="0"
                  class="vDateField"
                  min="0"
                  required=""
                  id="id_date_created"
                />
              </div>
            </div>

            <div class="form-row field-monto_prestado">
              <div>
                <label class="required" for="id_monto_prestado"
                  >Monto prestado:</label
                >

                <input
                  type="number"
                  name="monto_prestado"
                  value="0"
                  class="vIntegerField"
                  min="0"
                  required=""
                  id="id_monto_prestado"
                  
                />
              </div>
            </div>

            <div class="form-row field-interes">
              <div>
                <label class="required" for="id_interes"
                  >Interes:</label
                >

                <input
                  type="number"
                  name="interes"
                  value="0"
                  step="any"
                  required=""
                  id="id_interes"
                  
                />
              </div>

            </div>

            <div class="form-row field-num_meses">
              <div>
                <label class="required" for="id_num_meses"
                  >Num meses:</label
                >

                <input
                  type="number"
                  name="num_meses"
                  value="1"
                  class="vIntegerField"
                  min="0"
                  required=""
                  id="id_num_meses"
                />
              </div>
            </div>

            <div class="form-row field-tipo_pago">
              <div>
                <label class="required" for="id_tipo_pago"
                  >Tipo pago:</label
                >

                <div class="related-widget-wrapper">
                  <select
                    name="tipo_pago"
                    required=""
                    id="id_tipo_pago"
                    onchange="NumCuotas(event)"
                  >
                    <option value="" selected="">---------</option>

                    {% for tipo_pago in tipo_pagos %}
                    <option value="{{tipo_pago.pk}}">{{tipo_pago.tipo}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
            </div>

            <div class="form-row field-monto_a_pagar">
              <div>
                <label class="required" for="id_monto_a_pagar"
                  >Monto a pagar:</label
                >
                <input
                  type="number"
                  name="monto_a_pagar"
                  value="0"
                  class="vIntegerField"
                  min="0"
                  required=""
                  id="id_monto_a_pagar"
                  readonly
                />
                <script src="{% static 'js/loan/montoapagar.js' %}"></script>
              </div>
            </div>

            <div class="form-row field-num_cuotas">
              <div>
                <label class="required" for="id_num_cuotas"
                  >Num cuotas:</label
                >

                <input
                  type="number"
                  name="num_cuotas"
                  value="1"
                  class="vIntegerField"
                  min="0"
                  required=""
                  id="id_num_cuotas"
                />
                <script src="{% static 'js/loan/numeroCuotas.js' %}"></script>
              </div>
            </div>

            <div class="form-row field-deadline">
              <div>
                <label class="required" for="id_deadline"
                  >Deadline:</label
                >
                <input
                  type="date"
                  name="deadline"
                  class="vDateField"
                  size="10"
                  required=""
                  id="id_deadline"
                  spellcheck="false"
                  data-ms-editor="true"
                />
                <script src="{% static 'js/loan/dead_line.js' %}"></script>
              </div>
            </div>
          </fieldset>

          <div class="submit-row">
            <input
              type="submit"
              value="Save"
              class="default"
              name="_save"
            />

            <input
              type="submit"
              value="Save and add another"
              name="_addanother"
            />

          <script
            id="django-admin-form-add-constants"
            src="{% static 'js/loan/change_form.js' %}"
            data-model-name="loan"
            async=""
          ></script>

          <script
            id="django-admin-prepopulated-fields-constants"
            src="{% static 'js/loan/prepopulate_init.js' %}"
            data-prepopulated-fields="[]"
          ></script>
        </div>
      </form>
    </div>

    <br class="clear" />
  </div>
  <!-- END Content -->
{% endblock content %}

{% block footer %} 
<div id="footer"></div>
{% endblock footer %}

Backend/templates/loans/prestamos_crear.html
{% extends 'base.html' %} {% load static %} {% block title %}
<title>Add loan</title>

<link
  href="{% static 'css/autocomplete/jquery-ui.css' %}"
  rel="stylesheet"
  type="text/css"
/>
{% endblock title %}  {% block content %}
<!-- Content -->
<div id="content-main">
  <form
    method="post"
    id="loan_form"
    novalidate=""
    class="border border-secondary"
  >
    {% csrf_token %}

    <fieldset class="module aligned">
      <legend class="ml-4">
        <strong> Crear nuevo préstamo</strong>
      </legend>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_pk">
            <strong> <h5>ID:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input type="text" id="client-id" name="cliente" />
          <script>
            $(function () {
              var availableTags = [
                {% for cliente in clientes %}
                {
                  nombre: "{{cliente.nombre}}",
                  label: "{{cliente.pk}}",
                  last_name: "{{cliente.apellido}}",
                },
                {% endfor %}
                // "{{cliente.pk}} {{cliente.nombre}} {{cliente.apellido}}",
                // "{{cliente.nombre}}",
              ];
              $("#client-id")
                .autocomplete({
                  minLength: 0,
                  source: availableTags,
                  focus: function (event, ui) {
                    $("#client-id").val(ui.item.label);
                    return false;
                  },
                  select: function (event, ui) {
                    $("#cliente-name").val(ui.item.nombre + " " + ui.item.last_name);
                    $("#client-id").val(ui.item.label);
                    return false;
                  },
                })
                .autocomplete("instance")._renderItem = function (ul, item) {
                return $("<li>")
                  .append(
                    "<div>" +
                      item.label +
                      " " +
                      item.nombre +
                      " " +
                      item.last_name +
                      "</div>"
                  )
                  .appendTo(ul);
              };
            });
          </script>
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_cliente">
            <strong> <h5>Cliente:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input type="text" id="cliente-name" />
          <!-- <input type="hidden" id="client-id" name="cliente"> -->
          <script>
            $( function() {
                  var availableTags = [
                  {% for cliente in clientes %}
                  {
                    value: "{{cliente.pk}}",
                    label: "{{cliente.nombre}}",
                    last_name: "{{cliente.apellido}}",
                  },
                  {% endfor %}
                  // "{{cliente.pk}} {{cliente.nombre}} {{cliente.apellido}}",
                  // "{{cliente.nombre}}",
                  ];
                  $( "#cliente-name" ).autocomplete({
                                                  minLength: 1,
                                                  source: availableTags,
                                                  focus: function( event, ui ) {
                                                    $( "#cliente-name" ).val( ui.item.value + ' ' + ui.item.label + ' ' + ui.item.last_name );
                                                    return false;
                                                  },
                                                  select: function( event, ui ) {
                                                                                  $( "#cliente-name" ).val( ui.item.label + ' ' + ui.item.last_name );
                                                                                  $( "#client-id" ).val( ui.item.value );
                                                                                  return false;
                                                                                }
                                                })
                  .autocomplete( "instance" )._renderItem = function( ul, item ) {
                  return $( "<li>" )
                    .append( "<div>" + item.value + " " + item.label + " " + item.last_name + "</div>" )
                    .appendTo( ul );
                    };
              } );
          </script>
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_monto_prestado">
            <strong> <h5>Fecha de prestamo:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input
            type="date"
            name="date_created"
            value="0"
            min="0"
            required=""
            id="id_date_created"
          />
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_monto_prestado">
            <strong> <h5>Monto prestado:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input
            type="number"
            name="monto_prestado"
            value="0"
            min="0"
            required=""
            id="id_monto_prestado"
          />
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_interes">
            <strong> <h5>Interes:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input
            type="number"
            name="interes"
            value="0"
            step="any"
            required=""
            id="id_interes"
          />
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_num_meses">
            <strong> <h5>Num meses:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input
            type="number"
            name="num_meses"
            value="1"
            class="vIntegerField"
            min="0"
            required=""
            id="id_num_meses"
          />
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_tipo_pago">
            <strong> <h5>Tipo pago:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <select
            name="tipo_pago"
            required=""
            id="id_tipo_pago"
            onchange="NumCuotas(event)"
          >
            <option value="" selected="">---------</option>
            {% for tipo_pago in tipo_pagos %}
            <option value="{{tipo_pago.pk}}">{{tipo_pago.tipo}}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_monto_a_pagar">
            <strong> <h5>Monto a pagar:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input
            type="number"
            name="monto_adeudado"
            value="0"
            min="0"
            required=""
            id="id_monto_adeudado"
            readonly
          />
          <script src="{% static 'js/loan/montoapagar.js' %}"></script>
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_num_cuotas">
            <strong> <h5>Num cuotas:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input
            type="number"
            name="num_cuotas"
            value="1"
            min="0"
            required=""
            id="id_num_cuotas"
          />
          <script src="{% static 'js/loan/numeroCuotas.js' %}"></script>
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_deadline">
            <strong> <h5>Deadline:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input
            type="date"
            name="deadline"
            size="10"
            required=""
            id="id_deadline"
            spellcheck="false"
            data-ms-editor="true"
          />
          <script src="{% static 'js/loan/dead_line.js' %}"></script>
        </div>
      </div>
      
      <div>
        <input type="hidden" id="id_creador" name="creador" value ={{ user.pk }}  />
        {% comment %} <input type="number" id="id_monto_adeudado" name="monto_adeudado" value=""  /> {% endcomment %}
      </div>
      
    </fieldset>
    <div class="row float-left mt-3 ml-3">
      <button type="submit" class="btn btn-light ml-3 mr-3" name="save">
        <strong><h4>Guardar</h4></strong>
      </button>
      <button class="btn btn-light ml-3 mr-3">
        <strong><h4><a href="{% url 'loans-home' %}" class="text-dark">Cancel</a></h4></strong>
      </button>
    </div>
  </form>
</div>
<!-- END Content -->
{% endblock content %} {% block footer %}
<div id="footer"></div>
{% endblock footer %}

Backend/templates/loans/prestamos_home.html
{% extends '_base.html' %} {% load static %} {% block title %}
<title>Préstamos | Home</title>
{% endblock title %} 


{% block content %}
<div class="row float-left mt-1 ml-3 mb-1 mr-1">
  <h2><strong>Resumen de Prestamos</strong></h2>
</div>
  
<div class="row float-right mt-1 ml-3 mb-1 mr-1">
  <a class="p-2 text-dark" href="{% url 'loans-crear' %}">
    <img src="{% static 'images/base/add.png' %}" alt="" height="25"/>
  </a>
  
  <a class="p-2 text-dark" href="{% url 'loans-buscar' %}">
    <img src="{% static 'images/base/search3.png' %}" alt="" height="25"/>
  </a>
</div>

<table class="table">
  <thead>
    <tr class="h4 text-center">
      <th scope="col">Codigo prestamo</th>
      <th scope="col">Monto prestado</th>
      <th scope="col">Monto adeudado</th>
      <th scope="col">Numero de meses</th>
      <th scope="col">ID Cliente</th>
      <th scope="col">Nombre cliente</th>
    </tr>
  </thead>
  <tbody id="id_tabla_prestamo" class="h4 text-center">
  </tbody>
</table>
<script src="{% static 'js/loan/tabla_loan.js' %}"></script>
{% endblock content %}

Backend/templates/loans/tipopagos.html
{% extends '_base.html' %}
{%load static%}

{% block css %}
<!-- CSS -->
<link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock css %}

{% block title %}
<title>
Home
</title>
{% endblock %} 

{% block header%} 
{% if user.is_authenticated %} 
Hi {{ user.username }}!
<p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">login</a> |<a href="{% url 'signup' %}">signup</a>
{% endif %} {% endblock %}

{% block content %} 
<h3>Tipo pago Form</h3>
<hr />

<form action="" method="POST">
  {% csrf_token %} 

  <div class="form-row field-tipo_pago">
    <div>
      <label class="required" for="id_tipo_de_pago">Tipo de pago:</label>

      <div class="related-widget-wrapper">
        <select name="tipo_de_pago" required="" id="id_tipo_pago">
            <option value="" selected="">---------</option>
            {% for object in objects %}
            <option value="{{object.pk}}">{{object.tipo}}</option>
            {% endfor %}
        </select>
      </div>
    </div>
  </div>

  <input type="submit" />
</form>
{% endblock content %}